GET http://localhost:3000/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzg4ODY1NzEsInN1YiI6IjEifQ.c50ZlZ0Y0M9yMYbWuHvEfjX0Yx80LbIcsKAqNaVHYnc
