GET http://localhost:3000/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzg4ODYyNzMsInN1YiI6IjEifQ.0RPlVfVO1HL3OfoJ_E5trJUz-5wUfjoJF7MqDa6mb_0
